# Uncomment the next line to define a global platform for your project



target 'MyMealPrep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMealPrep

pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
